name: Development-Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - uses: "actions/upload-artifact@v3"
        with:
          name: "[DevBuild]-bSoulMMAddon"
          path: |
            bSMMA_v1/target/bSoulMMAddon_v1.jar
            bSMMA_v2/target/bSoulMMAddon_v2.jar
            README.yml
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.repository}}
          separator: "/"
      - name: Build passsed
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "${{ steps.split.outputs._0 }}"
          embed-title: "${{ github.actor }} pushed an update for ${{ steps.split.outputs._1 }}"
          avatar-url: "https://github.com/${{ steps.split.outputs._0 }}.png"
          embed-color: "65280"
          embed-author-name: "${{ github.actor }}"
          embed-author-url: "https://github.com/${{ github.actor }}"
          embed-author-icon-url: "https://github.com/${{ github.actor }}.png"
          embed-footer-text: "Build #${{github.run_number}} passed and waiting to be updated"
          embed-footer-icon-url: "https://i.imgur.com/D5KVghH.png"
          embed-description: |
            ${{ github.event.head_commit.message }}
            
            Download: [`Build #${{github.run_number}}`](https://nightly.link/${{github.repository}}/actions/runs/${{ github.run_id }}/[DevBuild]-bSoulMMAddon.zip)
            SpigotMC: [`102500`](https://www.spigotmc.org/resources/102500/)